### ISSUE TITLE
Maybe some mistakes on WebNLG reported scores

### ISSUE THREAD

**Issue by 131250208** [weizhepei/CasRel#14]
The paper reports 89.4, 92.2, 94.7, on WebNLG-Normal, WebNLG-EPO, WebNLG-SEO. But In my reproduction,  when the f1 score on WebNLG achieves 91.8 reported on the paper, it is hard to exceed 92.5 on WebNLG-SEO but easy to get 94.0 on WebNLG-EPO. It seems that the original paper may have mistaken the score on WebNLG-EPO with the score on WebNLG-SEO. I did a statistic, WebNLG-Normal, WebNLG-EPO, WebNLG-SEO separately have 246, 26, 457 samples and 246, 98, 1345 relation triplets. It is obvious that WebNLG-SEO is the main part, and it has 13 times triplets as WebNLG-EPO and 5 times as WebNLG-Normal. Given that WebNLG-Normal and WebNLG-EPO have a small number of triplets, so it seems little likely to drop the score down from 94.7 to 91.8.  So, it seems a little likely that CasRel achieves 91.8 on the entire WebNLG but 94.7 on WebNLG-SEO. 

Please check it again, Thanks~

**Comment by weizhepei** [comment]
Thank you for the constructive feedback! After re-running the experiments, I checked the experiment recording sheet and find the numbers for WebNLG are in line with my running. **Unfortunately, I confuse the numbers for SEO and EPO when drawing the figures**. 

Specifically, the numbers for WebNLG in Figure~3 should be:
Normal: 89.4
EPO: 94.7
SEO: 92.2

Instead of:
Normal: 89.4
EPO: 92.2
SEO: 94.7

We've addressed the figure issue and updated the paper on arxiv. Please refer to the [latest version](https://arxiv.org/abs/1909.03227). We appreciate it very much for your contribution to the paper!

**Comment by 131250208** [comment]
@weizhepei nice job!
