### ISSUE TITLE
关于subject

### ISSUE THREAD

**Issue by gao929165733** [weizhepei/CasRel#17]
sub_head, sub_tail = choice(list(s2ro_map.keys()))。为什么采样句子中的subject是随机选取其中一个，这样做的目的是什么呢，谢谢解答

**Comment by weizhepei** [comment]
Since we adopt a cascade two-step decoding process, such a setting makes it easier to proceed with the latter relation-specific object tagging part. You can refer to https://github.com/weizhepei/CasRel/blob/master/utils.py#L64 for a better understanding on how we deal with the multi-subject situation.
