### ISSUE TITLE
Does it support Chinese? and How can I develop the model?

### ISSUE THREAD

**Issue by fresh382227905** [weizhepei/CasRel#23]
Can you give me some suggestions and some tips？
Thanks!
Looking forward to your reply

**Comment by yulightnight** [comment]
maybe you just need to replace the pre-trained bert file and the training corpse.

**Comment by longlongman** [comment]
> Can you give me some suggestions and some tips？
> Thanks!
> Looking forward to your reply

I have made this model Chinese supported. Here is my [re-implement](https://github.com/longlongman/CasRel-pytorch-reimplement).

**Comment by yulightnight** [comment]
> > Can you give me some suggestions and some tips？
> > Thanks!
> > Looking forward to your reply
> 
> I have made this model Chinese supported. Here is my [re-implement](https://github.com/longlongman/CasRel-pytorch-reimplement).

thank you my pal~
a star is not enough for your great job!

**Comment by weizhepei** [comment]
Hi, @fresh382227905. To make the model support Chinese, you may need to change the pre-trained BERT and the [triple extraction part](https://github.com/weizhepei/CasRel/blob/master/utils.py#L46) (due to the different tokenization between English and Chinese) with minor revisions. You can also refer to @longlongman's great work : )
