### ISSUE TITLE
数据集文件需要修复

### ISSUE THREAD

**Issue by verylittlewhite** [weizhepei/CasRel#3]
CasRel/data/NYT/raw_NYT/generate.py

这个代码产生的文件所有的实体都只有一个词。比如New York，会变成York。

对于WebNLG也有同样的问题。

但是项目的README里面写的样本是正常的，说明是文件分享的问题，所以可以麻烦修复一下google drive分享的文件吗？谢谢！

**Comment by weizhepei** [comment]
Thank you for being interested in our work. For a fair comparison, we use the datasets (i.e., NYT and WebNLG) released by [CopyR](https://github.com/xiangrongzeng/copy_re) without any modification, and the google drive link is also provided by CopyR. As for the single-word-entity issue, you can find a discussion [here](https://github.com/xiangrongzeng/copy_re/issues/25). Note that we also conduct experiments on more datasets (which annotate the whole span of an entity instead of only the last word) as presented in the appendix of our paper. We actually discussed the differences among these datasets, including the single-word-entity issue. Please refer to our supplemental experiments and dataset study for more information. Feel free to reopen this issue if you have any new questions.

**Comment by verylittlewhite** [comment]
但是为什么readme里面的样本是正常的呢？

```
{
    "text": "Tim Brooke-Taylor was the star of Bananaman , an STV series first aired on 10/03/1983 and created by Steve Bright .",
    "triple_list_gold": [
        {
            "subject": "Bananaman",
            "relation": "starring",
            "object": "Tim Brooke-Taylor"
        },
        {
            "subject": "Bananaman",
            "relation": "creator",
            "object": "Steve Bright"
        }
    ],
    "triple_list_pred": [
        {
            "subject": "Bananaman",
            "relation": "starring",
            "object": "Tim Brooke-Taylor"
        },
        {
            "subject": "Bananaman",
            "relation": "creator",
            "object": "Steve Bright"
        }
    ],
    "new": [],
    "lack": []
}
```

我用有问题的数据集貌似跑不出来论文里的结果，所以论文里的结果应该是用正常的数据跑的？

**Comment by weizhepei** [comment]
The reason is that we present a **demo** data format in README where the whole span of the entity is annotated. However, please note that not all the datasets have annotated the whole span, as we pointed out above. So the details might be different among these datasets. 

Specifically, for NYT and WebNLG, only the last word is annotated. Hence, the format will be like:
```json
{
    "text": "Tim Brooke-Taylor was the star of Bananaman , an STV series first aired on 10/03/1983 and created by Steve Bright .",
    "triple_list_gold": [
        {
            "subject": "Bananaman",
            "relation": "starring",
            "object": "Brooke-Taylor"
        },
        {
            "subject": "Bananaman",
            "relation": "creator",
            "object": "Bright"
        }
    ]
}
```
For ACE04, NYT10-HRL, NYT11-HRL and Wiki-KBP, the whole span is annotated. Hence, the format will be like:
```json
{
    "text": "Tim Brooke-Taylor was the star of Bananaman , an STV series first aired on 10/03/1983 and created by Steve Bright .",
    "triple_list_gold": [
        {
            "subject": "Bananaman",
            "relation": "starring",
            "object": "Tim Brooke-Taylor"
        },
        {
            "subject": "Bananaman",
            "relation": "creator",
            "object": "Steve Bright"
        }
    ]
} 
```
It's hard to say the NYT and WebNLG datasets in CopyR are "problematic" or need to be "fixed", but I agree that only annotating the last word is not a standard way of preprocessing. To fairly compare our method with previous works on the two datasets, we directly use the public released datasets to train and test our model without any modification.

As for the performance issue, have you checked the hyperparameters and finished training? Please let me know if the F1-score on NYT keeps stucking at around 80%.

**Comment by verylittlewhite** [comment]
I see. I will check if there is something wrong with my running... Thanks for your reply!

**Comment by verylittlewhite** [comment]
I think I didn't run enough epochs before. Now it's ok!
