### ISSUE TITLE
Problems with Wiki-KBP dataset

### ISSUE THREAD

**Issue by 131250208** [weizhepei/CasRel#7]
We can only get a training dataset with 23k sentences from your link, but one with 79k sentences mentioned in your paper. Is there any problem with the link? Please check again. Or could you please send the 79K version training dataset to our email? (wangyucheng@iie.ac.cn) Just for a fair comparison, Thank you!

**Comment by weizhepei** [comment]
The link is ok, but you may need to process the 23k training data according to the instructions as described in their README:
```
python LabelGeneration/UIDExtractKB.py
python LabelGeneration/post_process_chunked_corpus.py
python LabelGeneration/applying_labelling_func.py --save_all
python LabelGeneration/applying_KB.py
python LabelGeneration/reCodeFuncs.py
python LabelGeneration/MergeLFS.py
python LabelGeneration/cal_Mention_Distance.py
python LabelGeneration/applyingInverse.py
```
The reason is that we follow the same setting as in line with previous works (e.g., PA-LSTM-CRF) for fair comparison ——“we use the public training data which are automatically labeled using distant supervision and handcrafted patterns by the author of (Liu et al. 2017)."

Thanks for your question, we will soon release the well-prepared datasets for better convenience so that people can skip the data preparation process and focus on the model itself.
