### ISSUE TITLE
关于ExactMatch问题

### ISSUE THREAD

**Issue by yiyi123123132** [weizhepei/CasRel#9]
你好：
       我在测试的时候选择了ExactMatch，但是结果还是实体只有头词。我查看了下训练数据和测试数据，好像所有实体都是头词，请问如果想看看ExactMatch，是否需要自己重新处理数据形成带有边界的训练数据，来完成ExactMatch？ 谢谢

**Comment by weizhepei** [comment]
For WebNLG and NYT, you may need to use StanfordNER to re-annotate the training and test data. Hope this [discussion](https://github.com/WindChimeRan/CopyMTL/issues/5) will help you to do the work.

For other datasets, since the whole span is annotated, so you can just switch the option to apply "Partial Match" or "Exact Match".
